### ISSUE TITLE
Add OJRock?

### ISSUE THREAD

**Issue by MPAQ-Admin** [CORTEXIMPLANT/webring#8]
I sent a request on the website but not sure if it worked and no idea how to do it here so, if you could, please add OJRock to the ring?

[
  {"name": "OJrock", "url": "http://ojrock.mpaq.org"},
]

Thank you.

**Comment by pionaiki** [comment]
This webring is for members of our Mastodon/Fedi community. You don't seem to be in it. Correct me if i'm wrong.
